### ISSUE TITLE
Reference numbers appearing twice

### ISSUE THREAD

**Issue by jvddorpe** [NFDI4Microbiota/nfdi4microbiota-knowledge-base#100]
See e.g. references at the bottom of the Data Reuse page.

**Comment by elhossary** [comment]
Fixed in the upcoming merge

**Comment by cpauvert** [comment]
This is due to the bibliography style. The extra numbers are from a HTML list and the second numbers are from the numeric style (see [message by the jekyll-scholar author](https://github.com/inukshuk/jekyll-scholar/issues/203#issuecomment-332290813).

I suggest moving to an author year style as it is also IMHO more informative in a an age where space restriction does not pushes for numeric style.

**Comment by elhossary** [comment]
This is now fixed by commenting the style "american-medical-association" that causing this issue in the _config.yml
